development:
  adapter: async

test:
  adapter: async
  # adapter: test

production:
  adapter: redis
  url: redis://redistogo:eebb524db9b7a6ca0a1a689793b3b003@scat.redistogo.com:10598/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: sezzle_backend_production
