development:
  adapter: async

test:
  adapter: async
  # adapter: test

production:
  adapter: redis
  url: redis://redistogo:7cf5579b069627ddced458bb6b6e9ff5@scat.redistogo.com:10768/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: sezzle_backend_production
